# Generated by Django 6.0 on 2025-12-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photo_tagged_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='watermarked_image',
            field=models.ImageField(blank=True, null=True, upload_to='watermark/'),
        ),
    ]
