# Generated by Django 6.0 on 2025-12-19 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_favourite_photo_is_favourite_of_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-add_to_fav_time_stamp']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-like_time_stamp']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-upload_time_stamp', '-taken_at']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tagged_user',
        ),
        migrations.AlterField(
            model_name='favourite',
            name='fav_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
