# Generated by Django 6.0 on 2025-12-19 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_alter_favourite_options_alter_like_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedUser',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tag_time_stamp'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='tagged_user',
            field=models.ManyToManyField(blank=True, related_name='tagged_In', through='photo.TaggedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='taggeduser',
            constraint=models.UniqueConstraint(fields=('user', 'photo'), name='unique_user_photo_tag'),
        ),
    ]
