# Generated by Django 6.0 on 2025-12-19 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_taggeduser_photo_tagged_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AlterField(
            model_name='favourite',
            name='fav_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
