# Generated by Django 6.0 on 2025-12-20 14:10

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_alter_favourite_options_alter_like_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-add_to_fav_time_stamp']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-like_time_stamp']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-upload_time_stamp', '-taken_at']},
        ),
        migrations.AddField(
            model_name='photo',
            name='downloaded_by',
            field=models.ManyToManyField(blank=True, related_name='downloaded_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='fav_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
