# Generated by Django 6.0 on 2025-12-22 22:58

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_alter_favourite_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='search_field',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='search_field',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
