# Generated by Django 6.0 on 2025-12-22 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_photo_search_field_tag_search_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='search_field',
        ),
    ]
