# Generated by Django 6.0 on 2025-12-28 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('event_name', 'event_date', 'event_coordinator'), name='unique_event_name_date_coordinator'),
        ),
    ]
