# Generated by Django 6.0 on 2025-12-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_type_alter_notification_text_message'),
        ('photo', '0016_remove_tag_search_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.photo'),
        ),
    ]
