# Generated by Django 6.0 on 2025-12-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_photo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='photo_id',
            new_name='photo',
        ),
    ]
