# Generated by Django 6.0 on 2025-12-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_rename_photo_id_notification_photo'),
        ('photo', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.comment'),
        ),
    ]
